binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
color = "Auto"
combine_control_expr = false
comment_width = 80
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
doc_comment_code_block_width = 80
edition = "2021"
empty_item_single_line = true
enum_discrim_align_threshold = 1
error_on_line_overflow = false
error_on_unformatted = false
fn_params_layout = "Tall"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = false
format_strings = false
hard_tabs = false
ignore = []
imports_granularity = "Crate"
imports_indent = "Block"
imports_layout = "Vertical"
indent_style = "Block"
match_arm_blocks = true
match_block_trailing_comma = true
max_width = 80
merge_derives = true
newline_style = "Auto"
normalize_comments = true
normalize_doc_attributes = false
overflow_delimited_expr = false
remove_nested_parens = true
reorder_impl_items = false
reorder_imports = true
reorder_modules = true
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 1
struct_lit_single_line = true
tab_spaces = 4
trailing_semicolon = false
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
version = "One"
where_single_line = false
wrap_comments = true
